# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form1.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form1(object):
    def setupUi(self, Form1):
        Form1.setObjectName("Form1")
        Form1.setWindowModality(QtCore.Qt.NonModal)
        Form1.resize(763, 450)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form1.sizePolicy().hasHeightForWidth())
        Form1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        Form1.setFont(font)
        Form1.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        Form1.setAcceptDrops(False)
        self.radio1 = QtWidgets.QRadioButton(Form1)
        self.radio1.setGeometry(QtCore.QRect(111, 7, 137, 17))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio1.sizePolicy().hasHeightForWidth())
        self.radio1.setSizePolicy(sizePolicy)
        self.radio1.setChecked(True)
        self.radio1.setObjectName("radio1")
        self.radio2 = QtWidgets.QRadioButton(Form1)
        self.radio2.setGeometry(QtCore.QRect(111, 30, 89, 17))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio2.sizePolicy().hasHeightForWidth())
        self.radio2.setSizePolicy(sizePolicy)
        self.radio2.setObjectName("radio2")
        self.etiqueta1 = QtWidgets.QLabel(Form1)
        self.etiqueta1.setGeometry(QtCore.QRect(12, 9, 93, 13))
        self.etiqueta1.setObjectName("etiqueta1")
        self.etiqueta2 = QtWidgets.QLabel(Form1)
        self.etiqueta2.setGeometry(QtCore.QRect(12, 56, 101, 13))
        self.etiqueta2.setObjectName("etiqueta2")
        self.comboBox = QtWidgets.QComboBox(Form1)
        self.comboBox.setGeometry(QtCore.QRect(111, 53, 121, 21))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.etiqueta3 = QtWidgets.QLabel(Form1)
        self.etiqueta3.setGeometry(QtCore.QRect(149, 84, 33, 13))
        self.etiqueta3.setObjectName("etiqueta3")
        self.cuarto = QtWidgets.QLineEdit(Form1)
        self.cuarto.setGeometry(QtCore.QRect(111, 81, 32, 20))
        self.cuarto.setObjectName("cuarto")
        self.tercero = QtWidgets.QLineEdit(Form1)
        self.tercero.setGeometry(QtCore.QRect(188, 81, 32, 20))
        self.tercero.setObjectName("tercero")
        self.segundo = QtWidgets.QLineEdit(Form1)
        self.segundo.setGeometry(QtCore.QRect(265, 81, 32, 20))
        self.segundo.setObjectName("segundo")
        self.primero = QtWidgets.QLineEdit(Form1)
        self.primero.setGeometry(QtCore.QRect(342, 81, 32, 20))
        self.primero.setObjectName("primero")
        self.ultimo = QtWidgets.QLineEdit(Form1)
        self.ultimo.setGeometry(QtCore.QRect(407, 81, 32, 20))
        self.ultimo.setObjectName("ultimo")
        self.etiqueta4 = QtWidgets.QLabel(Form1)
        self.etiqueta4.setGeometry(QtCore.QRect(226, 84, 33, 13))
        self.etiqueta4.setObjectName("etiqueta4")
        self.etiqueta5 = QtWidgets.QLabel(Form1)
        self.etiqueta5.setGeometry(QtCore.QRect(303, 84, 33, 13))
        self.etiqueta5.setObjectName("etiqueta5")
        self.etiqueta6 = QtWidgets.QLabel(Form1)
        self.etiqueta6.setGeometry(QtCore.QRect(380, 84, 33, 13))
        self.etiqueta6.setObjectName("etiqueta6")
        self.etiqueta7 = QtWidgets.QLabel(Form1)
        self.etiqueta7.setGeometry(QtCore.QRect(12, 84, 55, 13))
        self.etiqueta7.setObjectName("etiqueta7")
        self.etiqueta8 = QtWidgets.QLabel(Form1)
        self.etiqueta8.setGeometry(QtCore.QRect(12, 110, 47, 13))
        self.etiqueta8.setObjectName("etiqueta8")
        self.x1 = QtWidgets.QLineEdit(Form1)
        self.x1.setGeometry(QtCore.QRect(111, 107, 32, 20))
        self.x1.setObjectName("x1")
        self.y1 = QtWidgets.QLineEdit(Form1)
        self.y1.setGeometry(QtCore.QRect(176, 107, 32, 20))
        self.y1.setObjectName("y1")
        self.c1 = QtWidgets.QLineEdit(Form1)
        self.c1.setGeometry(QtCore.QRect(241, 107, 32, 20))
        self.c1.setObjectName("c1")
        self.x2 = QtWidgets.QLineEdit(Form1)
        self.x2.setGeometry(QtCore.QRect(111, 133, 32, 20))
        self.x2.setObjectName("x2")
        self.y2 = QtWidgets.QLineEdit(Form1)
        self.y2.setGeometry(QtCore.QRect(176, 133, 32, 20))
        self.y2.setObjectName("y2")
        self.c2 = QtWidgets.QLineEdit(Form1)
        self.c2.setGeometry(QtCore.QRect(241, 133, 32, 20))
        self.c2.setObjectName("c2")
        self.etiqueta9 = QtWidgets.QLabel(Form1)
        self.etiqueta9.setGeometry(QtCore.QRect(149, 110, 33, 13))
        self.etiqueta9.setObjectName("etiqueta9")
        self.etiqueta10 = QtWidgets.QLabel(Form1)
        self.etiqueta10.setGeometry(QtCore.QRect(214, 110, 33, 13))
        self.etiqueta10.setObjectName("etiqueta10")
        self.etiqueta11 = QtWidgets.QLabel(Form1)
        self.etiqueta11.setGeometry(QtCore.QRect(149, 136, 33, 13))
        self.etiqueta11.setObjectName("etiqueta11")
        self.etiqueta12 = QtWidgets.QLabel(Form1)
        self.etiqueta12.setGeometry(QtCore.QRect(214, 136, 33, 13))
        self.etiqueta12.setObjectName("etiqueta12")
        self.button1 = QtWidgets.QPushButton(Form1)
        self.button1.setGeometry(QtCore.QRect(111, 160, 75, 23))
        self.button1.setObjectName("button1")
        self.button2 = QtWidgets.QPushButton(Form1)
        self.button2.setGeometry(QtCore.QRect(192, 160, 75, 23))
        self.button2.setObjectName("button2")
        self.consola = QtWidgets.QPlainTextEdit(Form1)
        self.consola.setGeometry(QtCore.QRect(12, 212, 739, 226))
        self.consola.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.consola.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.consola.setReadOnly(True)
        self.consola.setObjectName("consola")

        self.retranslateUi(Form1)
        QtCore.QMetaObject.connectSlotsByName(Form1)

    def retranslateUi(self, Form1):
        _translate = QtCore.QCoreApplication.translate
        Form1.setWindowTitle(_translate("Form1", "Solucionador de Ecuaciones"))
        self.radio1.setText(_translate("Form1", "Sistema de 2 incognitas"))
        self.radio2.setText(_translate("Form1", "Sistema lineal"))
        self.etiqueta1.setText(_translate("Form1", "Tipo de ecuación:"))
        self.etiqueta2.setText(_translate("Form1", "Grado de ecuacion:"))
        self.comboBox.setItemText(0, _translate("Form1", "2"))
        self.comboBox.setItemText(1, _translate("Form1", "3"))
        self.comboBox.setItemText(2, _translate("Form1", "4"))
        self.etiqueta3.setText(_translate("Form1", "x^4 +"))
        self.etiqueta4.setText(_translate("Form1", "x^3 +"))
        self.etiqueta5.setText(_translate("Form1", "x^2 +"))
        self.etiqueta6.setText(_translate("Form1", "x +"))
        self.etiqueta7.setText(_translate("Form1", "Ecuación:"))
        self.etiqueta8.setText(_translate("Form1", "Sistema:"))
        self.etiqueta9.setText(_translate("Form1", "x +"))
        self.etiqueta10.setText(_translate("Form1", "y ="))
        self.etiqueta11.setText(_translate("Form1", "x +"))
        self.etiqueta12.setText(_translate("Form1", "y ="))
        self.button1.setText(_translate("Form1", "ADELANTE!"))
        self.button2.setText(_translate("Form1", "LIMPIAR!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form1 = QtWidgets.QWidget()
    ui = Ui_Form1()
    ui.setupUi(Form1)
    Form1.show()
    sys.exit(app.exec_())
